name: focal

on: [push]

jobs:
  build:
    env:
      PACKAGE_NAME: Base32Crockford
      SWIFT_VER: 5.2.4
      RELEASE_DOT: 20.04
      RELEASE_NUM: 2004

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    container:
      image: 'ubuntu:20.04'
      
    steps:
    - name: Install wget lsb-release
      run: sudo apt-get install -y wget lsb-release
    - uses: actions/checkout@v2
    #- name: Set Ubuntu Release DOT
    #  run: echo "::set-env name=RELEASE_DOT::$(lsb_release -sr)"
    #- name: Set Ubuntu Release NUM
    #  run: echo "::set-env name=RELEASE_NUM::${RELEASE_DOT//[-._]/}"
    - name: Download Swift 5.2.4
      run: curl -O https://swift.org/builds/swift-${SWIFT_VER}-release/ubuntu${RELEASE_NUM}/swift-${SWIFT_VER}-RELEASE/swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_DOT}.tar.gz
    - name: Extract Swift 5.2.4
      run: tar xzf swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_DOT}.tar.gz
    - name: Add Path
      run: echo "::add-path::$GITHUB_WORKSPACE/swift-${SWIFT_VER}-RELEASE-ubuntu${RELEASE_DOT}/usr/bin"
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test --enable-test-discovery --enable-code-coverage
    - name: Verify Valid Swift Package
      run: curl -s https://raw.githubusercontent.com/daveverwer/SwiftPMLibrary/master/script.sh | bash -s -- mine
    - name: Prepare Code Coverage
      run: llvm-cov export -format="lcov" .build/x86_64-unknown-linux-gnu/debug/${{ env.PACKAGE_NAME }}PackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash) -F github -F fossa -n ${{ github.sha }}
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
